### ISSUE TITLE
Do not download invalid WASM modules

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-fetcher#15]
When an HTTP server or OCI registry does not report an error, and instead returns a `200` HTTP status when downloading the Wasm module, contents are downloaded blindly and put into the store.

This should not happen, and we should double check that what we downloaded is a valid Wasm module, and error out if it's not the case.

**Comment by raulcabello** [comment]
This also happens when the http server returns a not found error `404`. Therefore users who made a typo in the url will experience this problem.

Steps to reproduce: 
- `kwctl pull https://github.com/kubewarden/pod-privileged-policy/releases/download/v0.1.9/policynotfound`
- Then `kwctl policies`                                                                                     
`Error: Bad magic number (at offset 0)`
